### ISSUE TITLE
Include xpath & severity from axe

### ISSUE THREAD

**Issue by mgifford** [GovTechSG/purple-a11y#238]
Axe includes the xpath in their csv reports, but Purple Hats does not. 

Xpaths are useful for identifying where there may be multiple instances across multiple pages. They are also very useful for finding the exact reference which was causing the error.

I also do think that the Critical, Serious, Moderate & Minor impact is useful. You split yours up into the WCAG vs Deque best practices which is useful to. However it should be possible to capture this:
https://github.com/dequelabs/axe-core/blob/develop/doc/issue_impact.md

I also liked how you had in earlier versions what types of disabilities were affected by a given SC.  That was useful. 

More data that may be usefu to folks:
https://github.com/CivicActions/accessibility-data-reference

**Comment by younglim** [comment]
Thanks @mgifford, considering your request.  It does make sense to add XPath and perhaps axe-severity rating to the CSV report for advanced users 👍

**Comment by younglim** [comment]
Hi @mgifford, we have added `xpath` and `axeImpact` rating to the CSV report in https://github.com/GovTechSG/purple-a11y/releases/tag/0.9.40

**Comment by mgifford** [comment]
this is great. Thanks!
