### ISSUE TITLE
Make it easier to find Sitemap.xml files that can be used.

### ISSUE THREAD

**Issue by mgifford** [GovTechSG/purple-a11y#258]
There are a number of sites that have sitemaps but it isn't always easy to find them from a list of URLs. 

To reduce the amount of time required to find them it would be helpful to have a script to seek out common places where sitemaps may be defined.

**Comment by mgifford** [comment]
You can see the simple python script here [https://github.com/GovTechSG/purple-a11y/pull/259/files](https://github.com/GovTechSG/purple-a11y/pull/259/files)  
  
Perhaps it would be better in node, but..

**Comment by mgifford** [comment]
Just moving this over here for consistency with the other tools: 
https://github.com/mgifford/purple-a11y/blob/master/sitemap-tools/sitemap-discovery.py

**Comment by younglim** [comment]
This has been implemented in intelligent scan mode `-c intelligent`. We will seek out supported sitemaps that Purple A11y supports today
