### ISSUE TITLE
01/03/2024 Not able to run on Windows 11

### ISSUE THREAD

**Issue by jcrain23** [GovTechSG/purple-a11y#262]
Hello,
I am currently able to run the 12/14 release, but I get an error with 01/03/2024 release. One of the changes must have had a negative impact, or the installation instructions need to be modified for something. I'm unsure.

Error:
{"timestamp":"2024-01-12 17:50:10","level":"error","message":"uncaughtException: Invalid URL\nTypeError: Invalid URL\n    at new URL (node:internal/url:775:36)\n    at getHost (file:///C:/Users/User/Desktop/Purple_A11Y_01032024/purple-a11y/utils.js:15:31)\n    at combineRun (file:///C:/Users/User/Desktop/Purple_A11Y_01032024/purple-a11y/combine.js:42:81)\n    at runScan (file:///C:/Users/User/Desktop/Purple_A11Y_01032024/purple-a11y/index.js:62:11)\n    at file:///C:/Users/User/Desktop/Purple_A11Y_01032024/purple-a11y/index.js:99:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}

**Comment by jcrain23** [comment]
Adding a screenshot to show how are I can get with an audit  
![image](https://github.com/GovTechSG/purple-a11y/assets/134228234/9bcadc6c-fbc7-49af-a92d-0db8c953bb12)

**Comment by younglim** [comment]
Thanks @jcrain23 for the feedback.  I will be creating a release soon to fix the issue.  The code fix needed is https://github.com/GovTechSG/purple-a11y/commit/10f7a735392121d59841c94f773ea2603fc5f849

**Comment by jcrain23** [comment]
@younglim Thank you! You rock!
