### ISSUE TITLE
Question, more than issue. Every scan results says "Website crawl (100 pages)". Is Purple A11Y limited to 100?

### ISSUE THREAD

**Issue by jcrain23** [GovTechSG/purple-a11y#383]
As the title mentions, all of my scan results say "Website crawl (100 pages)" on the left side of the HTML report. Is Purple A11Y limited to 100 pages? What concerns me is that it hasn't varied at all. I would expect some sites to have 98, others 130, etc... Is there a JS/Config file I can check or edit how many pages are scanned? Thanks in advance! I appreciate all you do for this app!

![image](https://github.com/GovTechSG/purple-a11y/assets/134228234/8cc2ab03-6438-46df-91b7-cb6c4e46bf6d)
![image](https://github.com/GovTechSG/purple-a11y/assets/134228234/c5bc41d8-b914-46d7-adf0-b370dc669625)

Thanks,
Jack

**Comment by younglim** [comment]
It is limited to 100 pages when running from `npm run start` . You can increase this limit by using `npm run cli ...` as documented at https://github.com/GovTechSG/purple-a11y?tab=readme-ov-file#cli-mode

**Comment by jcrain23** [comment]
@younglim Okay, thank you! We never realized that.
